### ISSUE TITLE
ShAvatar Issues

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#108]
### Style Properties
What are these three three style properties for and how can we manipulate them via `wrapper`? (assuming that it can be done) 
* `base`
* `socials`
* `icon`
* `avatar`

**Comment by FroudeDescartes** [comment]
We can manipulate all four of these through the `ui` styling (`ui.base`, `ui.socials`, `ui.icon` & `ui.avatar`). These are some examples of how some effects will be displayed targeting different class:

1. ### **`ui.base`**
Here and in the next class, `ui.socials`, I will just color the background of what is wrapped by them, so you will have a visual representation that may give some ideas on how can we manipulate these classes further

_**Update**: I have deleted the values for styling of the `base` since they had a minor impact on the overall looks. It is good option to have if we want to add some padding, margins, translate or anything else to the colored section on the picture below._
![image](https://github.com/standards-hub/docs/assets/128386451/56eea83d-bcd8-42c0-9471-39c5f7325605)
![image](https://github.com/standards-hub/docs/assets/128386451/f1b74a86-2d43-4d8e-a4aa-a9ca35f7a536)


2. ###  **`ui.socials`**
Here is the visual representation of what is wrapped by `ui.socials`
![image](https://github.com/standards-hub/docs/assets/128386451/d1f68e8e-7b3e-4e44-9a8d-916bdc820454)
![image](https://github.com/standards-hub/docs/assets/128386451/d2712315-8583-4008-acce-50376fa3947d)


3. ### **`ui.icon`**
Here we can add a certain color (I have added `hover:text-oma-500`) to the icons that will take place, in this case when we hover over them (see Facebook icon)
![image](https://github.com/standards-hub/docs/assets/128386451/91394120-0661-4c27-b56d-b36dc0abd974)
![image](https://github.com/standards-hub/docs/assets/128386451/d2788ed9-9f91-460a-ab47-3f0e1928f053)


4. ### **`ui.avatar`**
Here we can also apply some styles, but since we used grayscale for color of avatar, we are limited with colors. So here, I have added some shadow below avatar (`drop-shadow-2xl`)
![image](https://github.com/standards-hub/docs/assets/128386451/ee89d682-1a6c-445b-a540-d29726195e29)
![image](https://github.com/standards-hub/docs/assets/128386451/53d4c31a-cac9-4d74-b460-097c36fe3ce2)

**Comment by jpradocueva** [comment]
@FroudeDescartes, excellent! I will add these descriptions to the guidelines.
