### ISSUE TITLE
ShSegment: Comments

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#110]
After playing with the `ShSegment` I have noticed the following issues:

### Different Structure
The `front matter` bounded by (---) is set around the `ui` property and its attributes. The text or content is set between the last  (---)  and the (::). On the other constructors, e.g., `ShAvatar,` all the content is defined between (---).
- [x] Is there any reason why this constructor needs to work differently?
- [x] the values of the `wrapper` attribute are described without (`""`), but it is possible also to define them using (`""`); on the rest of the constructors, we need (`""`) when defining the values.

**Comment by FroudeDescartes** [comment]
> Is there any reason why this constructor needs to work differently?
1. Since this constructor for its content has only one input (and that input could be anything), Dejan opted out for `slot` element, which allows it to have a placeholder for anything that we want to populate with, including text with full MD support. Because of that, of that flexibility, this constructor`s use is a little bit different (no props at all).

> the values of the wrapper attribute are described without (""), but it is possible also to define them using (""); on the rest of the constructors, we need ("") when defining the values.
2. We can use either case, but we have agreed to take the less-typing option, so every constructor will be defined without them
