### ISSUE TITLE
ShColumn: Comments

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#112]
### Changes to Examples
@rubystream I have introduced some changes to the guidelines that describe this constructor.
I found it challenging to describe the constructor by using two columns. Instead, I used a basic and advanced constructor approach as we did previously with other constructors.  Please check it an critique as you see fit.

### Questions About Properties & Attributes
- [x] Is `header` an attribute we can configure its style? It is defined in the `sh-column.ts`, but I am unclear if we can style it like e.g., `wrapper`
- [x] Is `size` a property or an attribute? Can we style it?
- [x] Same for `main` is an attribute or property? can be styled? (it is defined in the `sh-column.ts` property.

### Footer Description in Advance Example
@rubystream In the advanced column example, we use a new constructor, `ShTwoColumns,` that has not been defined yet. Should we also define `ShTwoColumns` as a new constructor?

**Comment by FroudeDescartes** [comment]
@jpradocueva 
1. `header` is an object that contains `wrapper`, `title`, and `subtitle`. It is there so we can differentiate e.g. `wrapper` for the whole constructor and `wrapper` only for the `header` section. So basically, we cannot style `header` with classes but only objects inside of it. What could we do if we wanted to add class to header is either target the `header.wrapper` or we can concatenate classes like in the picture on the line 3

![image](https://github.com/standards-hub/docs/assets/128386451/fdddaff3-72c0-413d-9510-8cb598885a57)

___
2. `size` is a property with values of a whole number. This number represents an element in an array from `sh-grid-sizes.ts`. In this case, it takes the value of an element from `colSpan` array. So if we wanted to style it, we would have to change something in `sh-grid-sizes.ts`, but since the value of `size` is a number and it is used specially for grid, adding some other style in array would not make much sense.
___
3. `main` is an attribute with values of classes. It can be styled and it is to be found in `sh-column.ts` but it is currently without any values. We could add background to the `main` and only that section of constructor will have that bg

To answer the last question about `ShTwoColumns`; that constructor has been created and defined in `sh-two-columns.md`

**Comment by FroudeDescartes** [comment]
> Changes to Examples
@rubystream I have introduced some changes to the guidelines that describe this constructor.
I found it challenging to describe the constructor by using two columns. Instead, I used a basic and advanced constructor approach as we did previously with other constructors. Please check it an critique as you see fit.

I have added some more text, and moved things around so they follow the rest of components
