### ISSUE TITLE
Add two menus: Markdown & GitHub

### ISSUE THREAD

**Issue by jpradocueva** [standards-hub/docs#2]
Add two top menus for navigation

**Comment by jpradocueva** [comment]
@FroudeDescartes, I have created a new branch, `new-menus` that contains two more top-level menus, `home` and `process`
I have created a PR to see the content of the changes that I have applied. The menus are displayed at the top but I cannot render the content of the menus. What I am doing wrong?

**Comment by FroudeDescartes** [comment]
@jpradocueva 
Regarding a `Home` menu, when desiring to use a root file (index.md), there is no need to type the name of it, e.g.:

If we want to get `Home` menu to render text in `1.index.md` that is nested in folder
>1.getting-started
>--1.welcome-page
>----_dir.yaml
>----1.index.md
>----2.setup.md

our desired route path will be `/getting-started/welcome-page/`.

If we want to get to `2.setup.md `page then our route looks like this:
`/getting-started/welcome-page/setup`.

<hr/>

Now concerning `Process` menu, while declaring a route path, everything should be written in lower-case letters no matter the caps letters of a folder (thus is best practice to declare the folder name in lower-case letters as well).
I will be deleting your branch `new-menus` because it does not have updated work from Dejan, so it will probably result in a conflict for merge. However, I have created a new branch `test-new-menus` with PR where are all the same changes you have made with updated Dejan`s work.

**Comment by jpradocueva** [comment]
@FroudeDescartes, excellent, thanks. I see now that it works. I am closing this issue.
